#!/bin/bash
set -e -o pipefail

NUM_PARALLEL_PROCESSES=6

typescript_to_js() {
  set -x ; ./node_modules/.bin/tsc --noImplicitAny --noEmitOnError --target ES5 --module commonjs -d --sourceMap --noLib ./node_modules/typescript/bin/lib.es6.d.ts "$1"
}
export -f typescript_to_js

# Build everything in parallel.
find lib -name '*.ts' -a '!' -name '*.d.ts' -print0 | xargs -0 -n 1 -P $NUM_PARALLEL_PROCESSES -I FNAME bash -c "typescript_to_js FNAME"
