#!/bin/bash
set -e -o pipefail

NUM_PARALLEL_PROCESSES=6

typescript_to_js() {
  set -x ; ./node_modules/.bin/tsc --noEmitOnError --target ES5 --module commonjs -d --sourceMap --noLib ./node_modules/typescript/bin/lib.es6.d.ts "$1"
}
export -f typescript_to_js

babeljs() {
  set -x ; ./node_modules/.bin/babel --optional runtime --source-maps --stage 0 --out-file "${1/%.es6/.js}" "$1"
}
export -f babeljs

# Build everything in parallel.
{
  find lib -name '*.ts' -a '!' -name '*.d.ts'  -exec printf 'typescript_to_js %s\000' '{}' ';'
  find lib -name '*.es6' -exec printf 'babeljs %s\000' '{}' ';'
} | xargs -0 -n 1 -P $NUM_PARALLEL_PROCESSES bash -c
