#!/bin/bash
set -e -o pipefail -x

cd $(git rev-parse --show-toplevel)

# Transpile all TypeScript files.
./node_modules/.bin/tsc \
  --noImplicitAny \
  --noEmitOnError \
  --target ES5 \
  --module commonjs \
  --declaration \
  --sourceMap \
  --noLib \
  ./node_modules/typescript/bin/lib.es6.d.ts \
  ./typings/node/node.d.ts \
  --rootDir $PWD \
  lib/extractMessages.ts \
  web/index.ts

# Bundle files for browser.
# TODO: Source maps are broken.  We need to combine them together (use sorcery?)
./node_modules/.bin/cjsc web/index.js --minify --source-map='*.map' -o web/bundle.js --config web/cjsc_config.json
