#!/bin/bash
set -e -o pipefail

cd "$(git rev-parse --show-toplevel)"

BUILD_DIR="$PWD/build"

. ./scripts/build_rules.inc

set -x

# Spec files.
run_tsc ./typings/jasmine/jasmine.d.ts spec/*.ts
      
# Lib files.
run_tsc lib/extractMessages.ts web/index.ts

# Bundle files for browser.
IN=build/web/index.js OUT=build/web/bundle.js run_browserify_with_minify
